### ISSUE TITLE
Add function to create itemgetters from BibLaTeX bibliography files

### ISSUE THREAD

**Issue by andras-simonyi** [andras-simonyi/citeproc-el#1]

**Comment by denismaier** [comment]
That is maybe a bit off, but @joostkremers is working on adding support for CSL to [parsebib](https://github.com/joostkremers/parsebib). Don't know if that could help here.

**Comment by andras-simonyi** [comment]
Hi, thanks for the interest, I haven't  started to work on this feature yet, but it'd basically require implementing a mapping/translation between biblatex and CSL bibliography entries.  Fortunately, @denismaier has already described the mapping itself on the Wiki, so it shouldn't be a lot of work. I'll try to look into this in the next few days and provide some additional information. As for the WIP CSL support in parsebib, it can be absolutely relevant if it implements conversion between the two formats, I will have to check this as well.

**Comment by denismaier** [comment]
> As for the WIP CSL support in parsebib, it can be absolutely relevant if it implements conversion between the two formats, I will have to check this as well.

IIUC, this library parses both formats to hash maps. Maybe you could directly with the hash map?

**Comment by joostkremers** [comment]
> Hi, thanks for the interest, I haven't started to work on this feature yet, but it'd basically require implementing a mapping/translation between biblatex and CSL bibliography entries. Fortunately, @denismaier has already described the mapping itself on the Wiki, so it shouldn't be a lot of work.

Unfortunately, the mapping on the wiki doesn't seem to be complete. Most of the biblatex field names aren't mapped to anything. Or am I reading it wrong?

IIUC, the mapping is also not that straightforward, because CSL field names do not always map onto the same biblatex field name. So e.g., `container-title` maps to `booktitle` in an `InCollection` entry, but to `journaltitle` in an `Article` entry.

> I'll try to look into this in the next few days and provide some additional information. As for the WIP CSL support in parsebib, it can be absolutely relevant if it implements conversion between the two formats, I will have to check this as well.

Currently, I'm not planning to implement such a conversion, but if we have a complete mapping of biblatex entry types and fields to CSL entry types and fields, it shouldn't be too difficult to add.

**Comment by joostkremers** [comment]
> IIUC, this library parses both formats to hash maps. 

Yes, with the caveat that no conversion / unification is done (as just mentioned), so the code calling parsebib still needs to know if it's dealing with a `.bib` or a `.json` file.

**Comment by denismaier** [comment]
> Unfortunately, the mapping on the wiki doesn't seem to be complete. Most of the biblatex field names aren't mapped to anything. Or am I reading it wrong?

Hmm, it's been a while since I've worked on that mapping, and I've never finished it, mainly because the discussions about CSL support in orgmode got stuck somewhere around that time. But I can have a look again, or we can just use the mapping used by the sucessor to pandoc-citeproc.

**Comment by bdarcus** [comment]
> But I can have a look again, or we can just use the mapping used by the sucessor to pandoc-citeproc.

It does seem this mapping is likely the most difficult, and important work, and that it can and should be consolidated into one place.

**Comment by bdarcus** [comment]
> IIUC, the mapping is also not that straightforward, because CSL field names do not always map onto the same biblatex field name. So e.g., `container-title` maps to `booktitle` in an `InCollection` entry, but to `journaltitle` in an `Article` entry.

Yes, that's right.

But this makes mapping other formats, including biblatex, to csl json easier, while making it slightly harder to do the reverse.

**Comment by andras-simonyi** [comment]
A short update on this: The branch [1-biblatex_support](https://github.com/andras-simonyi/citeproc-el/tree/1-biblatex_support) now contains a new file `citeproc-biblatex.el` with an initial implementation of the biblatex->CSL mapping (mostly following Pandoc's). In addition, I've updated `oc-csl.el` to use this mapping with `*.bib` files --  for`*.bibtex` files the old `BibTeX->CSL` mapping is used. This new version can be found at https://gist.github.com/andras-simonyi/c79865da0b3252199b55d093f5a4ad64. 

My planned next steps are
- testing the new functionality and adding some automatic tests (most probably by adapting Pandoc's relevant ones),
- sending the `oc-csl.el`  patch to the Org mailing list,
- backporting `biblatex` support from `oc-csl` to `citeproc-org`.

**Comment by bdarcus** [comment]
I have your branch installed.

Do you have some good test org + bibltex files you can post?

That's the most time-consuming aspect of testing, TBH. With that, I can quickly test and confirm.

**Comment by andras-simonyi** [comment]
> I have your branch installed.
> 
> Do you have some good test org + bibltex files you can post?
> 
> That's the most time-consuming aspect of testing, TBH. With that, I can quickly test and confirm.

Actually, it's surprisingly difficult to find biblatex bibliographies useful for testing, the only one I'm aware of is  http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/examples/biblatex-examples.bib.

**Comment by andras-simonyi** [comment]
Having tested the converter a bit I've merged this branch into master. I'm sure there will be rough edges and specific issues in the (near?) future but closing this issue now as the basic infrastructure is in place.

**Comment by andras-simonyi** [comment]
> Hello, I would be very interested in this feature. Have you made any progress on this?
> 
> I would be willing to help if you have some pointers to what should be done to achieve BibLaTeX support.

@hugcis  Just FYI, in addition to adding (initial..) biblatex support to `citeproc-el`, I added a branch to `citeproc-org` which uses this feature, see the note in the README of the master branch. Would be interested in your feedback if you happen to try it out.
