### ISSUE TITLE
let*: Symbol’s function definition is void: when-let*

### ISSUE THREAD

**Issue by Quintus** [andras-simonyi/citeproc-el#104]
Dear Andras,

I recently switched my Linux distribution from Debian to OpenSUSE. This resulted in a downgrade of Emacs to version 25.3.1. Trying to export any document with citations now results in the error message shown in the attached logfile [bt.log](https://github.com/andras-simonyi/citeproc-el/files/8119488/bt.log). I tested with this org file `/tmp/mwe/mwe.org`:

~~~~~
#+TITLE: Test
#+AUTHOR: Testauthor
#+LANGUAGE: de
#+bibliography: /tmp/mwe/test.bib
#+cite_export: csl /tmp/mwe/juristische-schulung.csl

(org-html-export-as-html)

Test. [cite: Anschaulich anhand der Berechnung von Wettervorhersagen
@schölch2006cppat p. 973]
~~~~~

With this bib file:

~~~~ bibtex
@Article{schölch2006cppat,
	author = {Günther Schölch},
	title = {Patentschutz für computergestützte Entwurfsmethoden – ein Kulturbruch?},
	journaltitle = {Gewerblicher Rechtsschutz und Urheberrecht},
	shortjournal = {GRUR},
	year = {2006},
	pages = {969-976},
	langid = {ngerman}
}
~~~~

juristische-schulung.csl is [here](https://github.com/citation-style-language/styles/blob/e22b8a566bad9b4c7f52720f60dd875057a5d210/juristische-schulung.csl).

Version information:

~~~~
GNU Emacs 25.3.1 (x86_64-suse-linux-gnu, GTK+ Version 3.22.30) of 2021-09-21
Org mode version 9.5 (release_9.5-484-g98588e @ /home/quintus/.emacs.d/org-mode/lisp/)
citeproc-el @ ba49516265fa24b138346c4918d39d19b4de8a62 
~~~~

  -quintus

**Comment by denismaier** [comment]
Which opensuse? Tumbleweed had 27.2. If you're on Leap, in you can use a community package to install a recent emacs.

**Comment by Quintus** [comment]
Am Dienstag, dem 22. Februar 2022 schrieb Denis Maier:
> Which opensuse? Tumbleweed has 27.2. If you're on Leap, in you can use
> a community package to install a recent emacs.

I am on Leap 15.3, that is, current Leap. I know I can use alternate
ways to install current versions of Emacs, including compiling it from
source if desired, but since Andras recently mentioned that Emacs 25 is
still a target[1] I thought it is valid to report the problem as a bug
here.

Before I used Debian I was an ArchLinux and a Gentoo user, but I got
tired of rolling release several years ago. I’d rather not want to
return there.

  -quintus

[1]: https://github.com/andras-simonyi/citeproc-el/issues/102#issuecomment-1038420105

--
Dipl.-Jur. M. Gülker | https://mg.guelker.eu | PGP: Siehe Webseite
Passau, Deutschland  | ***@***.***    | O<

**Comment by andras-simonyi** [comment]
Hello, apologies for responding that late! Are you still on Emacs 25? If yes, I'll try to look into this now. (However note that Org itself doesn't officially support Emacs 25 anymore if I understand the situation correctly.)

**Comment by Quintus** [comment]
Am Sonntag, dem 19. Juni 2022 schrieb András Simonyi:
> Are you still on Emacs 25?

No, I compiled an Emacs 27.1 from source. That resolved the problem for
me.

  -quintus

**Comment by andras-simonyi** [comment]
Thanks, in view of the change in the Org requirements I also changed the earliest supported version to Emacs 26 so I'm closing the issue.
