### ISSUE TITLE
Support entry-spacing in latex output

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/citeproc-el#122]
The `entry-spacing` attribute appears to have no impact in latex output.

Can you fix that?

**Comment by andras-simonyi** [comment]
Yes, unfortunately, the support for global bibliography formatting options in the LaTeX formatter is rather partial currently (covers only hanging indent). I've just started working on this problem and expect to be able to provide better support shortly.

**Comment by andras-simonyi** [comment]
I've added a dedicated `org-latex` formatter here an also sent a corresponding patch to the Org mode mailing list. Together they should substantially improve LaTeX bibliography formatting.
