### ISSUE TITLE
CSL export not using local #+bibliography:

### ISSUE THREAD

**Issue by brittAnderson** [andras-simonyi/citeproc-el#132]
I have set `org-cite-global-biography` in my `init.el`. 

I then write a file for export with `org-publish` to html and where the org file has in the header `#+bibliography: "path-to-different-bib-file.bib"` I can `C-c C-c` and am told that the local environment has been updated, but when I export with `org-publish-project` the bib file being used is still the global one. If I manually do a `setq` and redefine I can use the other file. 

However I notice that if I try to insert a cite with `C-c C-x @` it lists for me entries from the locally defined bibliography so this seems to relate to the use of the `org-publish` exporter

**Comment by andras-simonyi** [comment]
I'm closing this issue here since the problem has been reported to the Org mailing list (see https://list.orgmode.org/87o7qmn7so.fsf@localhost).
