### ISSUE TITLE
Add new vars for CSL 1.0.2

### ISSUE THREAD

**Issue by denismaier** [andras-simonyi/citeproc-el#14]
I'm going to open a PR to add new variables that will be added in CSL 1.0.2. Is it correct that citeproc-el does not define regular variables? I've found the definitions for names, dates and numbers, but nothing for regular variables. Is that correct?

**Comment by andras-simonyi** [comment]
Yes, there is no list of standard variables, only of those that require special handling.

**Comment by denismaier** [comment]
Good. What about terms? How are they handled? Is there anything that needs to be done if new terms are added to the schema?

**Comment by andras-simonyi** [comment]
> Good. What about terms? How are they handled? Is there anything that needs to be done if new terms are added to the schema?

As far as I see the situation is similar, only those term names are hardwired which require special handling like "season-" and "month-".

**Comment by andras-simonyi** [comment]
Is there an official list of changes between CSL 1.01 and 1.02? I've found [this document](https://docs.google.com/document/d/1wY1cOOamDYYh8VNW7h_uleqieBDGOa_LYsRiVdQy1RI/edit#) but I'm not sure how up-to-date and comprehensive it is.

**Comment by denismaier** [comment]
I think there will be a changelog once the thing is officially announced as the current version. Until then, comparing the two branches of the schema repo is probably the best option.

**Comment by andras-simonyi** [comment]
I've merged the branch that added the new variables (see the linked PR above), so closing this issue.
