### ISSUE TITLE
Maintaining the original .bib source capitalization in titles

### ISSUE THREAD

**Issue by lazzalazza** [andras-simonyi/citeproc-el#142]
I see that `citeproc-el` might automatically alter the capitalization of titles (I have seen the discussion on the APA guidelines and I understand that this behavior could be intentional). I work in a different language (Italian) with different capitalization rules, and I would simply need to maintain the "raw" title of my entries. Is there a way to achieve that?

I'm exporting to html via org export and I don't know at what level the problem occurs, but seeing the past discussions I fear the issue might be caused by citeproc-el trying to adapt titles to the APA guidelines.

I am using a personal .csl  that doesn't specify the `title-case` attribute in the macro "title".

```
  <macro name="title">
    <text variable="title" font-style="italic"/>
   ...
  </macro>
```
If I tinker with the title-case attribuite I see changes as expected, but I cannot achieve an unaltered result.

This is the cite export command I use.

```
#+cite_export: csl path_to_my_personal.csl 
```
Is there any suggestion you might give me?

**Comment by andras-simonyi** [comment]
Hello, the cleanest (and, also, biblatex compatible) way of solving the problem would be setting the langid field of your Italian entries to "italian" (or anything else which is not on the `citeproc-blt--titlecase-langids` list). Is this an option?

**Comment by lazzalazza** [comment]
Hi, unfortunately not: I have to treat the whole of my bibliography the same, and I would like citeproc-el not to intervene on titles written in other languages either (plus, I have thousands of entries and modifying them all looks like a somewhat risky option).
Is there a way to inhibit the behavior generally?

**Comment by andras-simonyi** [comment]
I've now pushed a commit to org-mode's main branch which introduces a new user option, `org-cite-csl-bibtex-titles-to-sentence-case`, which can be used to turn off sentence-casing titles in entries that don't have an explicit English langid, so I'm planning to close this issue.
