### ISSUE TITLE
Error when loading `citeproc-generic-elements.el`

### ISSUE THREAD

**Issue by swflint** [andras-simonyi/citeproc-el#146]
I'm currently unable to load the library, receiving this error:

```
Debugger entered--Lisp error: (error "Eager macro-expansion failure: (wrong-type-argumen...")
  error("Eager macro-expansion failure: %S" (wrong-type-argument listp issued))
  internal-macroexpand-for-load((defalias 'citeproc--text #'(lambda (attrs context &rest _body) "Render the content of a text element with ATTRS an..." (let-alist attrs (let ((content nil) (type ...) (no-external-links ...)) (cond (\.value ...) (\.variable ...) (\.term ...) (\.macro ...)) (let (...) (citeproc-lib-maybe-stop-rendering ... context result ...)))))) t)
  load-with-code-conversion("/home/swflint/.emacs.d/citeproc/citeproc-generic-e..." "/home/swflint/.emacs.d/citeproc/citeproc-generic-e..." nil t)
  require(citeproc-generic-elements)
```

This is from 290320f.

**Comment by swflint** [comment]
With the following versions:
 - queue.el 0.2
 - s.el dda84d3b
 - f.el ab3ee381
 - dash 6db80c71
 - citeproc 290320f
 - emacs 29.1 (GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars))

I load as follows:
```elisp
(add-to-list 'load-path "~/.emacs.d/f.el")
(add-to-list 'load-path "~/.emacs.d/dash")
(add-to-list 'load-path "~/.emacs.d/s.el")
(add-to-list 'load-path "~/.emacs.d/lisp")
(add-to-list 'load-path "~/.emacs.d/citeproc")
(require 'citeproc)
```

Note, queue.el is in `~/.emacs.d/lisp`.

I receive this as the whole error:
```
Debugger entered--Lisp error: (error "Eager macro-expansion failure: (wrong-type-argumen...")
  error("Eager macro-expansion failure: %S" (wrong-type-argument listp issued))
  internal-macroexpand-for-load((defalias 'citeproc--text #'(lambda (attrs context &rest _body) "Render the content of a text element with ATTRS an..." (let-alist attrs (let ((content nil) (type ...) (no-external-links ...)) (cond (\.value ...) (\.variable ...) (\.term ...) (\.macro ...)) (let (...) (citeproc-lib-maybe-stop-rendering ... context result ...)))))) t)
  load-with-code-conversion("/home/swflint/.emacs.d/citeproc/citeproc-generic-e..." "/home/swflint/.emacs.d/citeproc/citeproc-generic-e..." nil t)
  require(citeproc-generic-elements)
  load-with-code-conversion("/home/swflint/.emacs.d/citeproc/citeproc.el" "/home/swflint/.emacs.d/citeproc/citeproc.el" nil t)
  require(citeproc)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)
```

**Comment by andras-simonyi** [comment]
The parsebib package (https://github.com/joostkremers/parsebib) is missing from the dependencies, but if I add it then I'm unable to reproduce the error -- with the exact same emacs and package versions you are using and without an init file (`emacs -q`) 

    (add-to-list 'load-path "~/.emacs.d/f.el")
    (add-to-list 'load-path "~/.emacs.d/dash.el")
    (add-to-list 'load-path "~/.emacs.d/s.el")
    (add-to-list 'load-path "~/.emacs.d/citeproc-el")
    (add-to-list 'load-path "~/.emacs.d/parsebib")
    (add-to-list 'load-path "~/.emacs.d/lisp")
    (require 'citeproc)

is executed without an error on my system (all I get is a `Package cl is deprecated` warning). Are you executing the above steps without loading any init files etc. before?

**Comment by swflint** [comment]
That's interesting.  I see the same thing when I add parsebib to a `test.el` and load without an init file.

I load parsebib in my normal configuration, and I still get the error.  Loading citeproc earlier in my init does not seem to help either.

**Comment by andras-simonyi** [comment]
Interesting indeed -- somehow the expansion of the `citeproc--text` function's `defun` throws an error in your case but I have no idea why exactly and cannot reproduce it with seemingly the exact same setup. Based on the error maybe you could try replacing the part 

````lisp
(if (string= .term "no date")
					(progn
					  (setq type 'present-var)
					  `(((rendered-var . issued)) ,cont))
				      cont)
````

simply with 

````
cont
````
and see what happens but this is a very long shot unfortunately.

**Comment by andras-simonyi** [comment]
Any update on this?

**Comment by swflint** [comment]
Apologies!  That does fix the error.

**Comment by swflint** [comment]
These are the results of `emacs --batch -L compat/ -L citeproc/ -L dash/ -L f.el/ -L s.el/ -L parsebib/ -L lisp/ -f batch-byte-compile citeproc/*.el`:

```
In toplevel form:
citeproc/citeproc-cite.el:32:11: Warning: Package cl is deprecated

In toplevel form:
citeproc/citeproc-generic-elements.el:92:4: Error: Wrong type argument: listp, issued
```

With

 - `citeproc` b704e7d
 - `compat`   ea8de2e
 - `dash.el`  6db80c7
 - `s.el`     dda84d3
 - `f.el`     ab3ee38
 - `parsebib` ace9df7
 - Emacs 29.1 (

**Comment by andras-simonyi** [comment]
Thanks, I've tried again and still couldn't reproduce. I've also added Emacs 29.1 to the list of CI target platforms and the current code compiles there without an error too. Also, I haven't received  any other report on the issue. I'm a bit unsure about how to proceed because I can try to come up with equivalent reformulations of the original code in the hope that it will compile on your system but it feels a bit risky to make modifications on the basis of a seemingly irreproducible problem.

**Comment by swflint** [comment]
I am still getting that error with the latest version.  In addition, I'm getting a new error:
> In toplevel form:
> citeproc/citeproc.el:41:2: Error: Eager macro-expansion failure: (wrong-type-argument listp issued)

**Comment by andras-simonyi** [comment]
Thanks, the whole thing is a mystery. I'm on the same platform (x86_64-pc-linux-gnu) as you, using the same Emacs version (29.1) and not seeing these problems at all, and there are no problems in the CI environment either.  Is citeproc-el the only Emacs package for which you are getting this type of compilation error? The only cases similar to this I've seen were situations in which bytecodes from different Emacs versions were mixed up, but I assume you are recompiling everything.

**Comment by swflint** [comment]
It is the only package for which I am getting that sort of error.

Until fairly recently, I did not compile *any* packages.  I've made sure that I delete bytecode for any/all packages, and I still get that error.

**Comment by andras-simonyi** [comment]
What is the source of your Emacs 29.1 binary? Is a it a package, or are you compiling Emacs on your system?

**Comment by swflint** [comment]
Precompiled package (NixOS package, no user-specified overrides (though package default is lucid toolkit)).

**Comment by swflint** [comment]
That seems rather unlikely, as I have (multiple times) removed all elc files before compiling.
