### ISSUE TITLE
could an updated release be made for melpa-stable?

### ISSUE THREAD

**Issue by bayesians-inc-PL** [andras-simonyi/citeproc-el#147]
There have been a few bugfixes that have been merged into `master` since version `0.9.3` from earlier this year. 

Could an updated version be released to melpa-stable?

**Comment by andras-simonyi** [comment]
Hello, thanks for raising this! Currently a few tests in the CSL test suite that ran OK on earlier Emacs versions throw errors on Emacs 29.1 and I want to fix them, but after that I'll definitely release a new stable version (in around two weeks).

**Comment by andras-simonyi** [comment]
I've just released  version 0.9.4.
