### ISSUE TITLE
Question/Help: how to render an isolated bibliography entry

### ISSUE THREAD

**Issue by suhail-singh** [andras-simonyi/citeproc-el#153]
Thank you for creating this library!

For my personal blog (which uses some customisations in addition to `ox-html`
and `ox-publish`), I would like to create and use an Org mode macro which given
a bibtex file (as set by `#+bibliography`), a CSL file (as set by
`#+cite_export`), and a bibtex reference, generates the HTML corresponding to
the bibliographic entry.  Specifically, I am interested in being able to
generate the HTML corresponding to `div.csl-entry > div.csl-right-inline` (i.e.,
the bibliographic entry without the bibliographic numbering).

Additionally, I would also like to modify the generated HTML in some specific
ways.  For instance, I would like to add `target="_blank"` to the links so that
any URLs in the rendered bibliographic entry (corresponding to the URL field of
the bibtex entry) open in a new tab.

One option would be to use something like `org-export-string-as` on a minimal
string (containing the citation) as below.

``` emacs-lisp
(org-export-string-as
   "#+bibliography: \"refs.bib\"
#+cite_export: csl \"./acm-sig-proceedings.csl\"
[cite:@iandola2016squeezenet]
#+print_bibliography:"
   'html t)
```

Having done the above, one can then post-process the generated HTML (in my case,
first to extract the HTML corresponding to the DOM element of interest and then
to tweak the HTML to add `target="_blank"`) as needed.

Is there a better way?  Ideally, no post-processing would be needed.

**Comment by andras-simonyi** [comment]
Hello, thanks for your interest in citeproc-el and  apologies for replying that late; unfortunately, in the last few weeks I have been extremely busy.  As for rendering a bibliography entry, have you tried simply using the bibentry citation style for that? (The shorthand is `cite/b`.)  Regarding modifying the generated html, the easiest way is  modify the html citeproc formatter, e.g., link formatting is specified by the 

       (href . ,(lambda (x y) (concat "<a href=\"" y "\">" x "</a>"))) 

cons cell in the `citeproc-fmt--html-alist` in `citeproc-formatters.el`. These alists are currently constant, but I can make them variables if that would be useful.

**Comment by andras-simonyi** [comment]
I think overriding `citeproc-fmt--html-alist` by a let binding doesn't work because it is a constant and citeproc-el is using lexical bindings. If `citeproc-fmt--html-alist` was defined with defvar instead of defconst than it would be a dynamically bound variable, this is why I suggested this change above.

As for the problem of isolated rendering, perhaps the simplest way would be using the method described in the "Rendering isolated references" section of the citeproc-el README, that way you can create a parsed style and a locale getter, and reuse those for rendering items. The items themselves can come from an appropriate item-getter, see the function `citeproc-hash-itemgetter-from-any` in ˙citeproc-itemgetters.el`.

**Comment by andras-simonyi** [comment]
Another thought: if you forgo Org, and use `citeproc-render-item` as I suggested, then you can define a new citeproc formatter by mostly copying the html formatter and making the modifications you need, register your formatter in `citeproc-fmt--formatters-alist`, which is already a variable, and use it as the format parameter of ˙citeproc-render-item˙.

**Comment by andras-simonyi** [comment]
> I don't believe that that's the reason. defconst in Elisp can be let-bound.

You are right, I thought constants are not bound dynamically when defined using lexical binding but, apparently, that isn't the case. Anyhow, here is an example what you could do using only citeproc-el:

````lisp
(require 'citeproc)

;; Create and register a 'modified-html' citeproc-el formatter 

(setq modified-html-alist
      (cons `(href . ,(lambda (x y) (concat "<a target=\'_blank\' href=\"" y "\">" x "</a>")))
	    citeproc-fmt--html-alist))

(push `(modified-html . ,(citeproc-formatter-create
			:rt (citeproc-formatter-fun-create modified-html-alist)
			:bib #'citeproc-fmt--html-bib-formatter))
      citeproc-fmt--formatters-alist)

;; Use the created formatter to render some items' bib entries

(let ((style (citeproc-create-style
	      "/path/to/style_to_use.csl" lg))
      (lg (citeproc-locale-getter-from-dir "/dir/to/csl_locales"))
      (ig (citeproc-hash-itemgetter-from-any "/path/to/bibtex.bib"))
      (items (funcall ig (list "bibtex_key_1" "bibtex_key_2"))))
  (mapcar (lambda (item) (citeproc-render-item (cdr item) style 'bib 'custom-html))
	  items))
````

**Comment by andras-simonyi** [comment]
Thanks for the suggestion and the correction, I'll probably add the snippet to the wiki and link to it from the README.

**Comment by andras-simonyi** [comment]
I plan to close this issue shortly in the absence of objections.
