### ISSUE TITLE
Journal titles exported incorrectly in sentence case with oscola.csl 

### ISSUE THREAD

**Issue by icaruszhu** [andras-simonyi/citeproc-el#159]
Dear Andras,

Many thanks for the wonderful package!  

I have encountered an issue for a while and I tried to trouble shoot myself with no success. 

When I export an bibliographic item using  the Oxford University Standard for Citation of Legal Authorities (OSCOLA)  (csl link:  https://github.com/citation-style-language/styles/blob/master/oscola.csl), the journal titles always appear incorrectly in sentence case, but they are meant to be in title case.

For example,  here is an item:
```
@article{nissenbaumProtectingPrivacyInformation1998,
  title = {Protecting {{Privacy}} in an {{Information Age}}: {{The Problem}} of {{Privacy}} in {{Public}}},
  shorttitle = {Protecting {{Privacy}} in an {{Information Age}}},
  author = {Nissenbaum, Helen},
  date = {1998},
  journaltitle = {Law and Philosophy},
  volume = {17},
  number = {5/6},
  pages = {559--596},
  publisher = {{Springer}},
  issn = {0167-5249},
 
}
```

The rendered result is as follows:
```
Helen Nissenbaum, “Protecting Privacy in an Information Age: The Problem of Privacy in Public” (1998) 17 Law and philosophy 559
```

The journal title should be in title case ("Law and Philosophy") rather than sentence case ("Law and philosophy").  I am not sure this is an issue with the csl file or citeproc or otherwise. 

Any advice on how to solve the above issue would be much appreciated!

**Comment by andras-simonyi** [comment]
Hello, I think the simplest solution is to modify the CSL style you are using. Concretely, if one changes line 425 of oscola.csl to 

````xml
<text variable="container-title" text-case="title"/>
````
than journal titles are rendered  in title case for articles.

**Comment by icaruszhu** [comment]
Andras, thank you so much!

The modification of the oscola.csl does work like a charm!
```
<text variable="container-title" text-case="title"/>
```
I have been struggling with this for a long time with many different attempts, none of which work previously. Your advice is deeply appreciated! (I am also thankful the line number of the oscola file is pinpointed. It just takes me 5 minutes to have this issue fixed.)

I think the the issue can be closed. !

**Comment by icaruszhu** [comment]
I will try to alert the CLS repostory to fix this.
