### ISSUE TITLE
Superfluous (?) message "SLICED:" in citeproc-s-sentence-case-title

### ISSUE THREAD

**Issue by lechten** [andras-simonyi/citeproc-el#164]
Currently, I get lots of output about SLICED text, probably from that line: https://github.com/andras-simonyi/citeproc-el/blob/0b56312227506d43493923a2fba6c436a659e377/citeproc-s.el#L163C22-L163C22

Can that be removed please?

**Comment by andras-simonyi** [comment]
Huh --  thanks for reporting, that was a debugging message which I've somehow forgotten to remove... Should be fixed by commit fed2853.

**Comment by lechten** [comment]
Thanks for the quick fix!
