### ISSUE TITLE
Failing to cite with original-date in brackets

### ISSUE THREAD

**Issue by wehlutyk** [andras-simonyi/citeproc-el#171]
First of all, thanks for this repo as it really makes Org / Pandoc citations available.

I'm trying to cite with an "original-date" value in Zotero's Extra field, exported to biblatex:
```
@book{simondonModeExistenceObjets2012,
  title = {Du mode d'existence des objets techniques},
  author = {Simondon, Gilbert},
  date = {2012},
  origdate = {1958},
  publisher = {Aubier},
  location = {Paris},
  isbn = {978-2-7007-0428-0},
  langid = {french},
  keywords = {\_tablet},
  annotation = {OCLC: 822212565},
  file = {/home/sl/Zotero/storage/P28L5BV4/Simondon_2012_Du mode d'existence des objets techniques.pdf}
}
```

Yet when cited in an org file `[cite:@simondonModeExistenceObjets2012]` and exported through org's pandoc "latex-pdf", the pdf gives
```
([[citeprocbibitem17 ][Simondon [1958] 2012]])
```
instead of the actual citation.

I'm guessing this comes from the inside `[` and `]`, and I couldn't find any citeproc-el tests taking the `original-date` into account.

Would there be a simple way to fix this? I'm happy to give more config details if needed (using doomemacs).

**Comment by andras-simonyi** [comment]
Thanks for the report! This looks like a more general problem with the Org Pandoc exporter, which seems to  be unable to handle correctly the brackets in the link description that citeproc-el generates. Exporting a link like 

    [[http://www.bbc.com][description [with] bracket]]

doesn't work properly either, despite being syntactically correct according to the official [Org Syntax specification](https://orgmode.org/worg/org-syntax.html):

> DESCRIPTION (optional)
>  One or more objects enclosed by square brackets. [..] It can contain square brackets, but not ]].

Note that this type of link can be exported without any problem using the built-in Org exporters including the LaTeX-based ones. I recommend submitting a bug report to the maintainers of the Pandoc Org exporter, or using the built-in LaTeX exporter. If you don't mind loosing the links between citations and bibliography items then a temporay workaround  could be turning off linking by setting the variable `org-cite-csl-link-cites` to nil.

**Comment by andras-simonyi** [comment]
Any update on this? As it doesn't seem to be a citeproc-el problem,  I plan to close this issue shortly if there are no objections.

**Comment by wehlutyk** [comment]
Sorry for the lag, yes that sounds fine to close! I just submitted this to ox-pandoc
