### ISSUE TITLE
Unexpected doi output in plain text export

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/citeproc-el#21]
Per list, I'm finding in this case a doi is getting output as an http link when using plain text export, and it makes no sense to me.

Details.

1. [chicago-note-bibliography-16th-edition.csl](https://github.com/citation-style-language/styles/blob/master/chicago-note-bibliography-16th-edition.csl)
2. [this json file](https://gist.github.com/bdarcus/98e6d3ef9be22e0912670469f04f28da)

citeproc-el output:

``` text
Low, Setha M. “The Edge and the Center: Gated Communities and the
Discourse of Urban Fear.” /American Anthropologist/ 103, no. 1 (March 1,
2001): 45–58. <https://doi.org/10.1525/aa.2001.103.1.45>.
```

pandoc output:

``` text
Low, Setha M. “The Edge and the Center: Gated Communities and the
Discourse of Urban Fear.” American Anthropologist 103, no. 1 (March 1,
2001): 45–58. doi:10.1525/aa.2001.103.1.45.
```

My reading of the style (see [here](https://github.com/citation-style-language/styles/blob/96e81147ccb3a6d86a8a89a57e9f615005f7e3b0/chicago-note-bibliography-16th-edition.csl#L1180), in particular) says the latter is correct, but I really can't understand why the former.

This is also what I see with the default chicago-author-date style, which does specify this sort of formatting:

``` text
Low, Setha M. 2001. “The Edge and the Center: Gated Communities and the
Discourse of Urban Fear.” /American Anthropologist/ 103
(1):45–58. <https://doi.org/10.1525/aa.2001.103.1.45>.
```

Clearly they are different styles.

~I also wondered if it was something about the export backend, but confirmed the same with HTML.~ (edit: sorry; made a mistake here)

Any other ideas?

Or can someone else confirm I'm not crazy (or maybe just over-tired!) here?

Edit: looking at this again next day, still doesn't seem right, but am still unsure why (I note, for example "doi" doesn't show up in the code base at all).

cc @denismaier

**Comment by andras-simonyi** [comment]
I think I managed to track this down. First of all, the issue doesn't affect html and latex Org exports, which use the html and latex output of citeproc-el directly, the problematic behavior occurs only when citeproc-el produces org output and this gets embedded in the Org document before exporting.  In the latter case, the Org exporter treats the doi links in the bibliography as it would any doi link in the document, and, apparently, this means converting them to urls by default. (I don't know what is the easiest way of turning this off.)

**Comment by bdarcus** [comment]
> I think I managed to track this down. First of all, the issue doesn't affect html and latex Org exports, which use the html and latex output of citeproc-el directly, the problematic behavior occurs only when citeproc-el produces org output and this gets embedded in the Org document before exporting. In the latter case, the Org exporter treats the doi links in the bibliography as it would any doi link in the document, and, apparently, this means converting them to urls by default. (I don't know what is the easiest way of turning this off.)

Thanks for looking into this!

I'm also glad I was wrong about it also happening with the HTML output; I got confused as I was switching styles.

If this doesn't happen with HTML and LaTeX, it's much less of an issue. But still, ideally it would work consistently.

**Comment by denismaier** [comment]
FWIW, the recommendation on doi.org is to uses the link format for DOIs anyway.  Do, I don't think that's much of a problem.
I don't know what the Chicago FAQ say about using DOIs in their old styles. Might be a good idea to look this up.

**Comment by bdarcus** [comment]
> FWIW, the recommendation on doi.org is to use the link format for DOIs anyway. So, I don't think that's much of a problem.
> I don't know what the Chicago FAQ say about using DOIs in their old styles. Might be a good idea to look this up.

I just checked; Chicago says the same.

But a) the visual formatted text is a style-side question, while b) is a processor-side. For the latter, see #22.

As a related, but separate, matter, seems we should get org-mode to link those doi links.

**Comment by andras-simonyi** [comment]
I think the issue has been addressed by implementing the external linking recommendations of the CSL 1.02 standard, so if there are no objections I'm going to close it soon.
