### ISSUE TITLE
Missing date bug?

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/citeproc-el#28]
I've mentioned this before, but am confirming with the merged version.

Source:

```org
#+language: en
#+cite_export: csl
#+bibliography: test.bib

[cite:@low2001]

#+print_bibliography:
```

Output:

```console
(Low, n.d.)

Low, Setha M. n.d. “The Edge and the Center: Gated Communities and the
Discourse of Urban Fear.” /American Anthropologist/ 103
(1):45–58. [https://doi.org/10.1525/aa.2001.103.1.45].


[https://doi.org/10.1525/aa.2001.103.1.45]
<https://doi.org/10.1525/aa.2001.103.1.45>
```

Biblatex file:

```bib
@article{low2001,
  author = {Low, Setha M.},
  title = {The Edge and the Center: Gated Communities and the Discourse
    of Urban Fear},
  journal = {American Anthropologist},
  volume = {103},
  number = {1},
  pages = {45-58},
  date = {2001-03-01},
  urldate = {2016-02-18},
  doi = {10.1525/aa.2001.103.1.45},
  issn = {1548-1433},
  langid = {en}
}
```

**Comment by andras-simonyi** [comment]
This may not be relevant at all but the components of the example don't really add up: the bibliographies don't seem to include any item with the key `ratto2014`.

**Comment by bdarcus** [comment]
Oops; sorry. Fixed.

**Comment by andras-simonyi** [comment]
Could you update the output as well?

**Comment by bdarcus** [comment]
Actually, though this doesn't appear to be the problem, I'm having problems getting the local bib to work, to ensure these all line up. 

What's wrong with this?

``` org
#+bibliography: test.bib
```

... or:

``` org
#+bibliography: ~/bib/test.bib
```

**Comment by andras-simonyi** [comment]
On my system all these ways of specifying the bib file work, and I don't get "n.d."-s in the citations instead of the year.

**Comment by bdarcus** [comment]
That's so weird.

You would think if I had one output problem it would be more pervasive.

I'll try reinstalling my packages and report back.

**Comment by andras-simonyi** [comment]
Well the package has support for running the whole CSL test suite, this could be a way of getting a more general picture of what is going on.

**Comment by bdarcus** [comment]
Something is just wrong. I reinstalled everything, and get the same behavior.

Local bibs don't work, and I get the same output, without dates.

How do I run the test suite?

**Comment by bdarcus** [comment]
Actually, I get it running with my emacs -Q script, which produces the same output. I've updated the main post.

``` console
GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-24
```

**Comment by andras-simonyi** [comment]
OK, now I understand. `citeproc-el` currently doesn't have built-in support for `biblatex` bibliographies, only for `BibTeX` proper. Concretely, the entry above uses a `date` field instead of `year`, which doesn't exist in `BibTeX` and gets ignored. I plan to add `biblatex` supporting functions soon (see issue #1), but in the meantime this is not a bug here -- maybe the documentation of `oc-csl` should emphasize more that `bibtex` means, well, `BibTeX` in the narrow sense, at least for now?

**Comment by bdarcus** [comment]
Sigh ... yeah, you're right. I neglected to test json using the reinstalled minimal example with emacs -Q. THAT does work as expected on my end.

But when I first reported, I was pretty sure I was seeing it with both json and bibltatex.

I'll experiment some more with my main install and json. It's likely there was just some issue on my end.

I'll close this now. Thanks for your patience.

Yes, #1, including possibly using the parsebib integrated biblatex/json support, would definitely be ideal.

**Comment by bdarcus** [comment]
Do you know, @andras-simonyi:

If I have the org global bibliography set, should not the local (to the document) bib override that?

**Comment by andras-simonyi** [comment]
> Do you know, @andras-simonyi:
> 
> If I have the org global bibliography set, should not the local (to the document) bib override that?

What I'm experiencing (with the CSL exporter) is that the local bibliography items are _added_ to the global ones, which is a bit surprising but not unreasonable IMO.

**Comment by bdarcus** [comment]
What does citeproc.el do if it has two input files that are exactly the same, but one is bib, and the other json?

I'd it default to json, that could be a workaround for me until you have biblatex support.

**Comment by andras-simonyi** [comment]
> What does citeproc.el do if it has two global input files that are exactly the same, but one is bib, and the other json?
> 
> If it defaults to json, that could be a workaround for me until you have better biblatex support.

This is stricty org-cite (amd citeproc-org) territory citeproc-el abstracts away everything about files and deals only with "item-getter" which are basically functions that return item data when called with an identifier.

**Comment by andras-simonyi** [comment]
biblatex bibliographies are now absolutely supported by citeproc-el, so date fields should be OK. Could you post the problematic bibliography entry?

**Comment by wuqui** [comment]
The problem was on my side of things, sorry. There were a couple of new moving parts for me (Zotero and the org-cite ecosystem) that weren't properly working together. In the end, I discovered that by bibliography got corrupted because of a couple of faulty date fields (e.g. _forthc._ for _forthcoming_).

Everything works find now and it's awesome! 👍
