### ISSUE TITLE
LaTeX citation styling.

### ISSUE THREAD

**Issue by tecosaur** [andras-simonyi/citeproc-el#34]
Hello,

I thought it would be nice to give CSL-generated LaTeX citations the same look as those generated by biblatex et. al.
I asked the hyperref folks if it would be possible to apply the same styling, and they got back to me :slightly_smiling_face: (see https://github.com/latex3/hyperref/issues/197).

So, the following should accomplish this:
```tex
\documentclass{article}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{colorlinks}

\makeatletter
\newcommand{\citeprocitem}[2]{\hyper@linkstart{cite}{#1}#2\hyper@linkend}
\makeatother

\begin{document}

\citeprocitem{citeproc_bib_item_foo}{foo}

\hypertarget{citeproc_bib_item_foo}{Foo, the journal of Foo...}

\end{document}
```

Though I'd also be tempted to shorten things like so:
```tex
\newcommand{\citeprocitem}[2]{\hyper@linkstart{cite}{citeproc_bib_item_#1}#2\hyper@linkend}
```

Thoughts?

**Comment by bdarcus** [comment]
+1 in general on improving default output.

Related to #24 also.

**Comment by andras-simonyi** [comment]
Thanks for raising this and for the suggested solution! As an experiment I've implemented it in the branch   [34-LaTeX_cite_link_styling](https://github.com/andras-simonyi/citeproc-el/tree/34-LaTeX_cite_link_styling). The reason I didn't use the more elegant custom-command based solution(s) you suggested is that `citeproc-el` in itself cannot touch the LaTeX preamble, so using something like `\citeprocitem` would break the current Org CSL export processor. In contrast, this could be merged immediately without any problems AFAICS. Of course, later we can try to switch `citeproc-el` and `oc-csl` simultaneously to the less verbose solution. WDYT?

**Comment by tecosaur** [comment]
Great :slightly_smiling_face:. Regarding the somewhat verbose solution currently used, perhaps we could extend `org-cite-csl-finalizer` in [oc-csl](https://code.orgmode.org/bzg/org-mode/src/master/lisp/oc-csl.el#L579) to add a bit more to the preamble and make this cleaner?

**Comment by andras-simonyi** [comment]
> Great slightly_smiling_face. Regarding the somewhat verbose solution currently used, perhaps we could extend `org-cite-csl-finalizer` in [oc-csl](https://code.orgmode.org/bzg/org-mode/src/master/lisp/oc-csl.el#L579) to add a bit more to the preamble and make this cleaner?

Yes, that is what I meant by switching `oc-csl`. I've already accumulated a number of patches but want to send them only when my Emacs copyright assignment paperwork gets sorted (it's in progress). Until then feel free to propose this patch against `oc-csl.el`and I can adapt `citeproc-el` whenever it's convenient.

**Comment by tecosaur** [comment]
I'll probably make a patch / PR or two then :slightly_smiling_face:

**Comment by andras-simonyi** [comment]
Perfect, thanks in advance!

**Comment by andras-simonyi** [comment]
A short update on this: it turns out that `\makeatletter` and `\makeatother` don't work inside footnotes (among others), so the only way forward is to define a special command in the preamble as you recommended, my verbose suggestion would break LaTeX export for all footnote styles.

**Comment by tecosaur** [comment]
I've finally got around to making that patch: https://lists.gnu.org/archive/html/emacs-orgmode/2021-08/msg00354.html

**Comment by andras-simonyi** [comment]
Thanks! I've just merged the corresponding change here -- closing the issue.
