### ISSUE TITLE
Which CSL tests are missing?

### ISSUE THREAD

**Issue by denismaier** [andras-simonyi/citeproc-el#36]
According to the readme this library currently covers 70% of the CSL test suite. What is still missing?

**Comment by andras-simonyi** [comment]
You can see all of the currently failing tests on the list [expected_fails,txt](https://github.com/andras-simonyi/citeproc-el/blob/master/test/expected_fails.lst). IIRC a large number of them is actually not about CSL proper, and many of them are irrelevant, although some covered functionality of course would be nice to have, like supporting formatting within some fields, e.g. titles.

**Comment by andras-simonyi** [comment]
I'd also move this to "Discussions" (because of its non-specificity) if you don't mind.

**Comment by denismaier** [comment]
> I'd also move this to "Discussions" (because of its non-specificity) if you don't mind.

Sure, go ahead!
