### ISSUE TITLE
textual citations

### ISSUE THREAD

**Issue by denismaier** [andras-simonyi/citeproc-el#38]
@ebouna and I realized today that textual citations aren't supported yet. Any chance they'll be added soon? Anything I can do to help here?

**Comment by andras-simonyi** [comment]
? they are supported... Maybe you are referring to support by the CSL processor in Org-cite? In that case you can find a "bleeding edge", patched drop-in replacement `oc-csl.el` at https://github.com/andras-simonyi/oc-csl-ns which supports all newly  added `citeproc-el` functionality among them textual citations. The plan is to send to accumulated patches to the Org mailing list for inclusion, but I'm still waiting for my signed  FSF copyright assignment papers to arrive.

**Comment by bdarcus** [comment]
```elisp
ELISP> (org-cite-supported-styles '(csl))
((("author" "a")
  ("caps-full" "cf")
  ("caps" "c")
  ("full" "f"))
 (("noauthor" "na")
  ("bare-caps" "bc")
  ("caps" "c")
  ("bare" "b"))
 (("year" "y")
  ("bare" "b"))
 (("text" "t")
  ("caps-full" "cf")
  ("full" "f")
  ("caps" "c"))
 (("nil")
  ("bare-caps" "bc")
  ("caps" "c")
  ("bare" "b")))
```

BTW, I just updated `bibtex-actions` to call that function. So as soon as the `oc-csl` updates are merged, the style UI will reflect that change.

Now just need to get annotation previews working again.

**Comment by bdarcus** [comment]
BTW, not sure if you all have any thoughts on this, but the screenshot reflects my experiments with offering hints to users to help them understand the style system.

So I highlight the main styles, for example, and de-emphasize the variant ones.

**Comment by andras-simonyi** [comment]
In the absence of objections I'm going to close this soon. BTW, I've activated the "Discussions" feature, if you wish to continue, well, the discussion :-).
