### ISSUE TITLE
Provide bibliographic data inline

### ISSUE THREAD

**Issue by denismaier** [andras-simonyi/citeproc-el#5]
It should also be possible to add bibliographic data inline, i.e. without a seperate bibfile. This is useful for shorter documents. With pandoc, bibliographic data can be added in a special metadate field, see <https://pandoc.org/MANUAL.html#citations>. Something similar should be possible with citeproc-el/citeproc-org.

**Comment by andras-simonyi** [comment]
(This might interest @bdarcus  as well.) There are actually (at least) two means to have inline bibliographies in Org-mode documents right now: the first, very general way is using an Org source block for the bibliography which is tangled to a separate bibliography file and has produces no output during export. The second, perhaps more interesting solution is based on the fact that citeproc-el/oc-csl/citeproc-org have recently acquired the ability to directly use `org-bibtex` bibliographies (see, e.g., http://gewhere.github.io/org-bibtex) so one can have a non-exported section in the Org file in which all subheadings describe bibliography entries using attributes which is used as the bibliography when the file is exported.

**Comment by andras-simonyi** [comment]
I've created a Wiki page with the response above, so will close this issue if there are no objections.

**Comment by denismaier** [comment]
Sure, go ahead.
