### ISSUE TITLE
Support *relative* CSL file names

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [andras-simonyi/citeproc-el#60]
My usage of `citeproc-el` is nowaday mostly via the `[cite:...]` feature of `org-mode`. My suggestion might be in `org-mode` territory. Or I might bark up the wrong tree...

In this implementation, the CSL style file *must* be an **absolute** file reference. This might be a pain if the relevant file has a long path. It might even be impossible (e. g. : acceding a file "in the Cloud", such as a Google drive, or a SMB/CIFS file with no drive letter in Windows).

Could `citeproc` accept *relative* references, such as (Linux examples, I don't have enough Windows fu to create correct examples) : 

```
#+cite_export: MyLocal.csl
#+cite_export: MySubdir/MyLocal.csl
#+cite_export: $MyProject/utils/MyCustom.csl
#+cite_export: cifs://myserver/Myservice/MyUtils//MyCustom.csl
```

Having to specify an absolute path is but an annoyance, but not a minor one...

Cordially,

**Comment by andras-simonyi** [comment]
This definitely looks like something which could (should?) be implemented on the Org side -- resolving relative file names requires information about the context (relative to what?) and the context will vary from application to application, e.g., in Org could be the path of the Org document, a setting etc.

**Comment by andras-simonyi** [comment]
In the absence of objections I'm going to close this soon.
