### ISSUE TITLE
Map `type` to `genre` for `@jurisdiction`

### ISSUE THREAD

**Issue by Quintus** [andras-simonyi/citeproc-el#65]
Dear all,

I would like to request that for `@jurisdiction` entries in Biblatex .bib files (-> `legal_case` in CSL) the `type` key is mapped to CSL's `genre` variable. The CSL style [juristische-schulung.csl](https://github.com/citation-style-language/styles/blob/e22b8a566bad9b4c7f52720f60dd875057a5d210/juristische-schulung.csl) uses `genre` to differenciate the two major kinds of court decisions we have in German process law (“Urteil”, meaning there has been an oral hearing before the decision, and “Beschluss”, meaning there was none).

Currently I am abusing the `note` key with a custom adapted version of `juristische-schulung.csl`, but that doesn't quite cut it. `genre` seems much more sensible.

  -quintus

**Comment by Quintus** [comment]
Example for a case entry in my .bib Biblatex files:

~~~~~ bibtex
@Jurisdiction{bgh2013usedsoft-ii,
  author       = {BGH},
  type        = {Urteil},
  number       = {I ZR 129/08},
  eventdate    = {2013-07-17},
  shortjournal = {GRUR},
  journaltitle = {Gewerblicher Rechtsschutz und Urheberrecht},
  year = {2014},
  pages = {264-272},
  title     = {UsedSoft II},
  commentator = {Malte Stieper}
}
~~~~~

**Comment by andras-simonyi** [comment]
Thanks for the suggestion! I've just merged a PR implementing this.

**Comment by Quintus** [comment]
Works like a charm! Thank you so much.

  -quintus
