### ISSUE TITLE
Locator treated as prefix

### ISSUE THREAD

**Issue by Quintus** [andras-simonyi/citeproc-el#68]
Dear all,

take this org file `mwe.org`:

~~~~~~ org
#+TITLE: Test
#+AUTHOR: Testauthor
#+LANGUAGE: de
#+bibliography: /tmp/mwe/mwe.bib
#+cite_export: csl /tmp/mwe/juristische-schulung.csl

Das ist ein Test [cite:@redeker2020itr Kap. A Rn. 72, Suffixtext hier]
~~~~~~

with this `mwe.bib` Biblatex file:

~~~~~~ bibtex
@Book{redeker2020itr,
author       = {Helmut Redeker},
title        = {IT-Recht},
year      = {2020},
edition   = {7},
publisher = {C.H. Beck},
location  = {München},
langid    = {ngerman}}
~~~~~~

juristische-schulung.el is https://github.com/citation-style-language/styles/blob/e22b8a566bad9b4c7f52720f60dd875057a5d210/juristische-schulung.csl

When this is exported to HTML, the locator `Kap. A Rn. 72` is split and partly taken as the prefix. It exports to this:

~~~~~~~
1 Kap. A Rn.  Redeker, IT-Recht, 7. Aufl. (2020), 72 Suffixtext hier
~~~~~~~

This is incorrect; it should export to:

~~~~~~~
1 Redeker, IT-Recht, 7. Aufl. (2020), Kap. A Rn. 72 Suffixtext hier
~~~~~~~

Org mode version 9.5 (release_9.5-214-gced2b3 @ /home/quintus/.emacs.d/org-mode/lisp/)

citeproc.el at 38e70c0a94eeefe86ddefc38dfa8ab2311008774

**Comment by andras-simonyi** [comment]
Thanks for raising the issue! For better or worse, parsing a cite into prefix, locator and suffix is done entirely on the Org-mode side, so you should probably send a report to the Org mailing list.

**Comment by Quintus** [comment]
Thanks for the hint. Done: https://list.orgmode.org/87ee7nkwds.fsf@atlantis/T/#u
