### ISSUE TITLE
Package cannot be found

### ISSUE THREAD

**Issue by sati-bodhi** [andras-simonyi/citeproc-el#8]
`M-x package-list-packages F` failed to show `citeproc-el`. 

Emacs version: 26.2 (9.0)

Settings: 

```
(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
	("melpa-stable" . "https://stable.melpa.org/packages/")
        ("gnu" . "https://elpa.gnu.org/packages/")
        ("org" . "http://orgmode.org/elpa/")))
(package-initialize)
```

**Comment by andras-simonyi** [comment]
Hello, sorry for responding only now. Somewhat confusingly, the package's name is `citeproc` and not `citeproc-el `. I ran an Emacs 26.1 instance with your init settings and the package `citeproc` was present in the package list  as expected: version 0.1.1 from melpa stable and version 20190422.2017 from melpa. Do you see other packages from melpa and melpa-stable but not `citeproc`?

**Comment by sati-bodhi** [comment]
`M-x list-packages F` and `M-x package-install` lists just `mu-cite`. 

Doing a `C-s` I-search for `cite-proc` in `list-packages` however showed me this: 

![圖片](https://user-images.githubusercontent.com/7592695/64577180-45c7c100-d3ae-11e9-94f8-12017dcd68b1.png)

There is even a package by the same name which I've installed earlier. 

![圖片](https://user-images.githubusercontent.com/7592695/64577367-b7a00a80-d3ae-11e9-9af2-7f85b24b21d1.png)

**Comment by andras-simonyi** [comment]
Yes, this is the package. Meanwhile the version changed in melpa since I've merged a pull request (currently it is 20190909.1948) but as far as I can see there are no problems with the package and it is available.

**Comment by andras-simonyi** [comment]
...so if there are no objections on your part I close this issue.

**Comment by sati-bodhi** [comment]
This is not a bug, but a separate personal issue.  

As I am relatively new to `Elisp` programming, could you provide me with a working example of the code so that I can test on my own? I work with `org` and `bib(la)tex` files. 

Sample code I am currently trying out: 
```
(require 'citeproc)

(citeproc-itemgetter-from-bibtex "sample.bib")
(citeproc ("~/Zotero/styles/humanities-chinese.csl"))
```
csl:

https://gist.github.com/sati-bodhi/31dd24dd280c88d51908

bib(la)tex: 
```
@book{陳鼓應YiChuanYuDaoJiaSiXiang1994,
  langid = {pinyin},
  location = {{台北}},
  title = {易傳與道家思想},
  isbn = {978-957-05-0994-6},
  pagetotal = {382},
  publisher = {{臺灣商務印書館}},
  date = {1994},
  author = {陳鼓應},
  eprinttype = {googlebooks}
}

@incollection{徐復觀YinYangWuXingJiQiYouGuanWenXianDeYanJiu1969,
  location = {{臺北}},
  title = {陰陽五行及其有關文獻的研究},
  booktitle = {中國人性論史（先秦篇）},
  publisher = {{商務}},
  date = {1969},
  pages = {509-587},
  author = {{徐復觀}}
}
```

Sample `org` citation: 
```
[@徐復觀YinYangWuXingJiQiYouGuanWenXianDeYanJiu1969{555-563}]；cite:陳鼓應YiChuanYuDaoJiaSiXiang1994
```
To be rendered as:

>徐復觀〈陰陽五行及其有關文獻的研究〉，收入《中國人性論史》，頁555-563。陳鼓應，《易傳與道家思想》（台北：臺灣商務印書館，1994年）。

**Comment by andras-simonyi** [comment]
Apart from having an `org` output formatter (among a few others), `citeproc-el` is independent of `org`, so if you are specifically interested in using `citeproc-el` with `org` then you might wish to look into [citeproc-org](https://github.com/andras-simonyi/citeproc-org), which integrates citeproc-el into `org` as a citation and bibliography renderer.

As for a working example for your data, it could go along the following lines (using global variables for simplicity, in real code these would be locals):

```emacs-lisp
;; create an itemgetter for the bibliography
(setq itemgetter (citeproc-itemgetter-from-bibtex "sample.bib"))

;; create a locale getter using a directory containing the required csl locales
(setq localegetter (citeproc-locale-getter-from-dir "locales"))

;; create a citation processor
(setq cproc (citeproc-create "humanities-chinese-footnote-tw.csl"
			     itemgetter localegetter))

;; create some cites
(setq cite1 '((id . "徐復觀YinYangWuXingJiQiYouGuanWenXianDeYanJiu1969")
	      (locator . "555-563"))
      cite2 '((id . "陳鼓應YiChuanYuDaoJiaSiXiang1994")))

;; create two citations containing the cites
(setq citation1 (citeproc-citation-create :cites (list cite1))
      citation2 (citeproc-citation-create :cites (list cite2)))

;; add the citations to the processor's stored list of citations
(citeproc-append-citations (list citation1 citation2) cproc)

;; show the list of rendered citations in the minibuffer
(message "%s" (citeproc-render-citations cproc 'plain))
```

**Comment by sati-bodhi** [comment]
If you look at the csl file I shared above, locale settings are already incorporated in it. Does this make any difference to this line in the code? 
```
;; create a locale getter using a directory containing the required csl locales
(setq localegetter (citeproc-locale-getter-from-dir "locales"))
```
Or do I have to set up my own locale directory for things to work?

**Comment by andras-simonyi** [comment]
Unfortunately, it's obligatory to supply a locale getter function to the citation processor constructor, even if the CSL style contains a full locale.  If the locale-getter function is created with the `citeproc-locale-getter-from-dir` convenience function, then yes, you have to set up your own locale directory, but it does not have to contain all CSL locale files, the one referenced in the used style is usually enough.

**Comment by sati-bodhi** [comment]
It worked - but part of the csl definition didn't turn out correctly. 

>"(徐復觀，〈陰陽五行及其有關文獻的研究〉，收入《中國人性論史（先秦篇）》（商務），頁555–563 陳鼓應，《易傳與道家思想》（臺灣商務印書館）)"

compare with: 

>徐復觀〈陰陽五行及其有關文獻的研究〉，收入《中國人性論史》，頁555-563。陳鼓應，《易傳與道家思想》（台北：臺灣商務印書館，1994年）。

location and date needs to be cited with the publisher.

**Comment by andras-simonyi** [comment]
The differences are due to the fact that the bibliography is using Biblatex fields instead of the ones require by BibTeX. If you switch to BibTeX field names ("date" -> "year", "location" -> "address") then I think the rendering will be correct.

**Comment by sati-bodhi** [comment]
Yes, it is. I can't wait to try out `citeproc-org`.  Thank you for your great work and support!
