### ISSUE TITLE
Support literal names in CSL-JSON

### ISSUE THREAD

**Issue by sopoforic** [andras-simonyi/citeproc-el#99]
I see that #72, marked as fixed by PR #78, added support for e.g. company names from bibtex files, but this does not seem to work with CSL-JSON files. I have a citation for a video game with data like:

```json
"author":[{"literal":"Atlus Co., Ltd."}],
```

When this is exported to HTML, no name appears (so I just get `(1987)` rather than `Atlus Co., Ltd. (1987)` as expected).

**Comment by andras-simonyi** [comment]
Thanks for reporting this, I've merged a PR (#100) which adds support for CSL-JSON lteral names as well.

**Comment by sopoforic** [comment]
Thanks! I can confirm that this is working correctly, now.
